.\" Manpage for hethio-server.
.\" Contact daniel@moranit.com to correct errors or typos.
.TH man 8 "{DATESTAMP}" "{VERSION}" "hethio-server man page"
.SH NAME
hethio-server \- Monitor your reports from agents in the field.
.SH SYNOPSIS
hethio-server
.SH DESCRIPTION
hethio-server is daemon that monitors various datapoints from the hethio agents environment.  
.SH OPTIONS
The hethio-server does not take any options.
.SH SEE ALSO
N/A
.SH BUGS
No known bugs.
.SH AUTHOR
Daniel H Moran (daniel@moranit.com)