#!/bin/sh
#
# This script typically stops any daemons which are associated with a package. 
# It is executed before the removal of files associated with the package.
#
echo "<prerm>"

# Stop hethio-server service if it exists
if [ -f /etc/init.d/hethio-server ]; then
	echo "Stopping service."
	chmod +x /etc/init.d/hethio-server
	/etc/init.d/hethio-server stop
fi
